on: [push, pull_request]
name: Continuous integration
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Check
    strategy:
      matrix:
        fn:
          - functions/add-endpoint
          - watcher
          - cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check --manifest-path ${{ matrix.fn }}/Cargo.toml

  test:
    name: Test Suite
    strategy:
      matrix:
        fn:
          - functions/add-endpoint
          - watcher
          - cli

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test --manifest-path ${{ matrix.fn }}/Cargo.toml

  fmt:
    name: Rustfmt
    strategy:
      matrix:
        fn:
          - functions/add-endpoint
          - watcher
          - cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: dtolnay/rust-toolchain@stable
      - run: rustup component add rustfmt
      - run: cargo test --manifest-path ${{ matrix.fn }}/Cargo.toml

  clippy:
    name: Clippy
    strategy:
      matrix:
        fn:
          - functions/add-endpoint
          - watcher
          - cli
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup component add clippy
      - run: cargo clippy --manifest-path ${{ matrix.fn }}/Cargo.toml -- -D warnings
